### ISSUE TITLE
unicom_lightCat_restart.py  login err

### ISSUE THREAD

**Issue by qgbcs** [Yihy/Shell_Script#1]
```
Traceback (most recent call last):
  File "unicom_lightCat_restart.py", line 105, in <module>
    cookie = login(domain, password)
  File "unicom_lightCat_restart.py", line 27, in login
    login_check_token, login_token, cookies = get_login_check_token(domain)
  File "unicom_lightCat_restart.py", line 16, in get_login_check_token
    login_check_token = result[0]
IndexError: list index out of range

```

**Comment by qgbcs** [comment]
Frm_Loginchecktoken

**Comment by qgbcs** [comment]
Frm_Logintoken: 6
Frm_Loginchecktoken: 680686280429740276170315
Right: 
Username: CMCCAdmin
UserRandomNum: 98993771
Password: f598f8372e117766616f2f5942d415cae14633c9c190001f92864f4dabce0515
action: login

**Comment by jianyun8023** [comment]
This script is outdated, the Unicom optical modem page has changed, and I no longer have the corresponding equipment. If you have the technical skills, you can analyze the logic of logging in and restarting in the browser's debug mode and write your own.
